### ISSUE TITLE
User Oriented Features

### ISSUE THREAD

**Issue by pratikpatelx** [pratikpatelx/AnswerBot#12]
- [x] Select summary and high quality answer paragraphs based on user behaviour patterns

- [x] Paragraph Position - Set a paragraph's summary value to be inversely propotional to the paragraph's position in the post for the first m paragraphs.
_**summary = 1/pos (1 <= pos <= m) where m = 3 in our implementation**_

- [x] Vote on Answer - Set an answer paragraph's vote as the vote on the answer post from which the paragraph is extracted

**Comment by swetul** [comment]
All features implemented, closing feature...
