### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by pratikpatelx** [pratikpatelx/AnswerBot#15]
- **We need to calculate the overall score based on the 7 features implemented**
- The overall score is computed as:
- The answer for each answer paragraph by multiplying the normalized value of each feature
-
Please see normalization.py it needs to be optimized, still contains alot of bugs @swetul

**Comment by pratikpatelx** [comment]
@swetul working on that implementation

**Comment by swetul** [comment]
@pratikpatelx completed the implementation.
Closing issue...
