### ISSUE TITLE
Text Preprocessing 2: Tokenizing the text corpus

### ISSUE THREAD

**Issue by pratikpatelx** [pratikpatelx/AnswerBot#4]
- [x] Use a library to tokenize the sentences in the text corpus

- [x] Update the text corpus

- [x] Build a Word2Vec model using Genism to learn the word embedding model on this text corpus

**Comment by pratikpatelx** [comment]
Building the Word2Vec model done please see build_vocabulary.py for additional details @pratikpatelx @swetul

**Comment by pratikpatelx** [comment]
@swetul

**Comment by swetul** [comment]
Final version of File resolve added. see tokenize_text.py
