### ISSUE TITLE
Assymetric Relevance Algorithm

### ISSUE THREAD

**Issue by pratikpatelx** [pratikpatelx/AnswerBot#8]
- [x] Implement Algorithm that computes the asymmetric relevance using bag of words for query q and Question Q

**Comment by pratikpatelx** [comment]
- [x] Implement Ways to get the Question Q based on user input i.e dynamically
- [x] Preprocess Questions  from DB                                             
- [x] Do bag of Words and store it 

@swetul

**Comment by pratikpatelx** [comment]
- [x]  Implement Ways to get the Tile query q  based on user input i.e dynamically
- [x] Preprocess that query from DB
- [ ] Do bag of Words and store it

@swetul

**Comment by pratikpatelx** [comment]
- [x] Pass the Bag of Words Model for Question and Query to Relevance Calculation Algorithm
@swetul

**Comment by pratikpatelx** [comment]
Method routines for calculating the Asymmetric and Symmetric relevance have been completed please see **RelevantQuestion/test.py** file. @swetul

**Comment by pratikpatelx** [comment]
### Note: To make sure the relevance algorithms work please generate the Word2Vec model by running the Word2VecModel/build_vocabulary.py file

@swetul

**Comment by swetul** [comment]
Steps mentioned above complete. Added support for real-time and training question retrieval. 
see "user_query.py"

**Comment by pratikpatelx** [comment]
> * [x]  Implement Ways to get the Question Q based on user input i.e dynamically
> * [x]  Preprocess Questions  from DB
> * [x]  Do bag of Words and store it
> 
> @swetul

Completed By Swetul
